CREATE DATABASE BANCO_DE_DADOS;

CREATE TABLE CLIENTE (ID_CLIENTE SERIAL CONSTRAINT PK_ID_CLIENTE PRIMARY KEY NOT NULL,
  NOME VARCHAR (255) NOT NULL,
  DATA_NASCIMENTO DATE NOT NULL,
  EMAIL VARCHAR (255) NOT NULL  
);

SELECT * FROM CLIENTE; 